//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class crew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crew()
        {
            this.crew_whitelist = new HashSet<crew_whitelist>();
        }
    
        public string barcode { get; set; }
        public string crew_name { get; set; }
        public System.DateTime assign_date { get; set; }
        public string crew_status { get; set; }
        public string crew_airport { get; set; }
        public string company_airways { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crew_whitelist> crew_whitelist { get; set; }
    }
}
