//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crew_whitelistEntities : DbContext
    {
        public crew_whitelistEntities()
            : base("name=crew_whitelistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<crew> crews { get; set; }
        public virtual DbSet<crew_whitelist> crew_whitelist { get; set; }
    }
}
